[package]
name = "starknet-abigen-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow.workspace = true         
starknet.workspace = true
starknet-abigen-parser.workspace = true
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0.15"
serde_json = "1.0.74"
